spring:
  application:
    name: FoodLore-Backend

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:food-lore
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
jwt:
  expiry: 3000000000
  secret: c3mwXUR8RC3ugnWmfDe1rPo8vufFuE7pbkCUumG2o4M=